// export const SIGN_UP_WITH_EMAIL_START = "SIGN_UP_WITH_EMAIL_START";
export const SIGN_UP_WITH_EMAIL_SUCCESS = "SIGN_UP_WITH_EMAIL_SUCCESS";
export const LOGIN_WITH_EMAIL_SUCCESS = "LOGIN_WITH_EMAIL_SUCCESS";
// export const SIGN_UP_WITH_EMAIL_FAIL = "SIGN_UP_WITH_EMAIL_FAIL";


export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const LOADING_START = "LOADING_START";
export const LOADING_STOP = "LOADING_STOP";